# Generated by Django 3.1.2 on 2020-10-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendbook', '0003_auto_20201022_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend_images',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
