# Generated by Django 3.1.2 on 2020-10-22 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendbook', '0004_auto_20201022_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userfollower', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
