# Generated by Django 3.1.2 on 2020-10-22 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendbook', '0005_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='following',
            field=models.ManyToManyField(related_name='zac', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followers',
            name='userfollower',
            field=models.ManyToManyField(related_name='joy', to=settings.AUTH_USER_MODEL),
        ),
    ]
